spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DATABASE_NAME:weazle_time_tracking}
    username: ${DB_USERNAME:username}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml