name: Build the WeazleTimeTrackingApplication

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  checkout:
    name: Checkout the project source files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  build-backend:
    name: Build the Java Backend
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  build-frontend:
    name: Build the VueJS Frontend
    needs: checkout
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Use Node.js 22.12
        uses: actions/setup-node@v4
        with:
          node-version: "22.12"
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present