name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-backend:
    name: Build the Java Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "temurin"
          cache: maven
          cache-dependency-path: "./backend/pom.xml"
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  build-frontend:
    name: Build the VueJS Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.12
        uses: actions/setup-node@v4
        with:
          node-version: "22.12"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"
      - run: npm ci
      - run: npm run build --if-present

